version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/postgres
    depends_on:
      - db

volumes:
  pgdata:
